-- Generated by Lockstamp. Review before applying.
-- Apply as a new migration (supabase migration new guard_fix) or paste into the Supabase SQL editor.
begin;

-- public.app_settings: Row Level Security was off, so anyone with the public key could reach every row.
alter table "public"."app_settings" enable row level security;
-- No owner column found: read-only for now. Remove this rule if the table should not be public.
drop policy if exists "guard: public read-only" on "public"."app_settings";
create policy "guard: public read-only" on "public"."app_settings" for select to anon, authenticated using (true);

-- public.notes: these rules let users reach other users' rows.
drop policy if exists "Enable insert for authenticated users only" on "public"."notes";
drop policy if exists "Enable read access for all users" on "public"."notes";
drop policy if exists "guard: owners can read" on "public"."notes";
create policy "guard: owners can read" on "public"."notes" for select to authenticated using ((select auth.uid()) = "user_id");
drop policy if exists "guard: owners can add" on "public"."notes";
create policy "guard: owners can add" on "public"."notes" for insert to authenticated with check ((select auth.uid()) = "user_id");
drop policy if exists "guard: owners can update" on "public"."notes";
create policy "guard: owners can update" on "public"."notes" for update to authenticated using ((select auth.uid()) = "user_id") with check ((select auth.uid()) = "user_id");
drop policy if exists "guard: owners can delete" on "public"."notes";
create policy "guard: owners can delete" on "public"."notes" for delete to authenticated using ((select auth.uid()) = "user_id");

-- public.profiles: Row Level Security was off, so anyone with the public key could reach every row.
alter table "public"."profiles" enable row level security;
-- Each user can only see their own row. If other users need to see these rows (e.g. names on posts), add a read rule for that.
drop policy if exists "guard: owners can read" on "public"."profiles";
create policy "guard: owners can read" on "public"."profiles" for select to authenticated using ((select auth.uid()) = "id");
drop policy if exists "guard: owners can add" on "public"."profiles";
create policy "guard: owners can add" on "public"."profiles" for insert to authenticated with check ((select auth.uid()) = "id");
drop policy if exists "guard: owners can update" on "public"."profiles";
create policy "guard: owners can update" on "public"."profiles" for update to authenticated using ((select auth.uid()) = "id") with check ((select auth.uid()) = "id");
drop policy if exists "guard: owners can delete" on "public"."profiles";
create policy "guard: owners can delete" on "public"."profiles" for delete to authenticated using ((select auth.uid()) = "id");
-- Users may edit only safe columns of public.profiles; role can only be changed by your server.
revoke insert, update on "public"."profiles" from anon, authenticated;
grant insert ("id", "full_name", "avatar_url", "created_at") on "public"."profiles" to authenticated;
grant update ("full_name", "avatar_url") on "public"."profiles" to authenticated;

-- public.subscriptions: Row Level Security was off, so anyone with the public key could reach every row.
alter table "public"."subscriptions" enable row level security;
-- Billing records: users can read their own rows; only your server or an admin function can change them.
drop policy if exists "guard: owners can read" on "public"."subscriptions";
create policy "guard: owners can read" on "public"."subscriptions" for select to authenticated using ((select auth.uid()) = "user_id");

-- public.note_counts: the view ran with its creator's permissions and skipped Row Level Security.
alter view "public"."note_counts" set (security_invoker = true);

-- public.get_all_emails(): reads your users table with full permissions. Only your server can call it now.
revoke execute on function "public"."get_all_emails"() from public, anon, authenticated;

commit;
