import { apiPolicies, autoFixable } from "./checks.js";
import { qualified, quoteIdent } from "./introspect.js";
import type { DbSchema, Table } from "./types.js";

const WRITE_COMMANDS = ["INSERT", "UPDATE", "DELETE", "ALL"];

export function buildFix(schema: DbSchema): string {
  const body: string[] = [];

  for (const t of schema.tables) {
    const q = qualified(t.schema, t.name);
    const reachable = t.access.anon.length > 0 || t.access.authenticated.length > 0;
    const rules = apiPolicies(t);
    let usersCanWrite = false;

    if (!t.rlsEnabled && reachable) {
      body.push("", `-- ${t.schema}.${t.name}: Row Level Security was off, so anyone with the public key could reach every row.`);
      body.push(`alter table ${q} enable row level security;`);
      body.push(...accessRules(t));
      usersCanWrite = ownerWritable(t);
    } else if (t.rlsEnabled) {
      const replaced = rules.filter((p) => autoFixable(t, p));
      if (replaced.length > 0) {
        body.push("", `-- ${t.schema}.${t.name}: these rules let users reach other users' rows.`);
        for (const p of replaced) body.push(`drop policy if exists ${quoteIdent(p.name)} on ${q};`);
        body.push(...accessRules(t));
        if (replaced.some((p) => p.cmd === "ALL") && t.exposure !== "private") {
          body.push("-- The removed rule also let everyone read this table; reading stays open until you decide otherwise.");
          body.push(...rule(q, "guard: public read-only", "for select to anon, authenticated using (true)"));
        }
      }
      const remainingWrites = rules.some((p) => !replaced.includes(p) && WRITE_COMMANDS.includes(p.cmd));
      usersCanWrite = remainingWrites || (replaced.length > 0 && ownerWritable(t));
    }

    const tableLevelWrite = t.access.authenticated.includes("UPDATE") || t.access.authenticated.includes("INSERT");
    if (usersCanWrite && !t.sensitive && t.protectedColumns.length > 0 && tableLevelWrite) {
      body.push(...columnGrants(t));
    }
  }

  for (const v of schema.views) {
    if (v.materialized || v.securityInvoker || !v.apiReadable) continue;
    body.push("", `-- ${v.schema}.${v.name}: the view ran with its creator's permissions and skipped Row Level Security.`);
    body.push(`alter view ${qualified(v.schema, v.name)} set (security_invoker = true);`);
  }

  for (const f of schema.functions) {
    if (!f.readsAuthUsers || (!f.anonCanExecute && !f.authenticatedCanExecute)) continue;
    body.push("", `-- ${f.schema}.${f.name}(): reads your users table with full permissions. Only your server can call it now.`);
    body.push(`revoke execute on function ${qualified(f.schema, f.name)}(${f.args}) from public, anon, authenticated;`);
  }

  if (body.length === 0) return "-- Lockstamp: no automatic fixes needed.\n";

  return [
    "-- Generated by Lockstamp. Review before applying.",
    "-- Apply as a new migration (supabase migration new guard_fix) or paste into the Supabase SQL editor.",
    "begin;",
    ...body,
    "",
    "commit;",
    "",
  ].join("\n");
}

export function tablesChangedByFix(schema: DbSchema): Set<string> {
  const changed = new Set<string>();
  for (const t of schema.tables) {
    const reachable = t.access.anon.length > 0 || t.access.authenticated.length > 0;
    const rules = apiPolicies(t);
    const tableLevelWrite = t.access.authenticated.includes("UPDATE") || t.access.authenticated.includes("INSERT");
    const columnLock = !t.sensitive && t.protectedColumns.length > 0 && tableLevelWrite && rules.some((p) => WRITE_COMMANDS.includes(p.cmd));
    if ((!t.rlsEnabled && reachable) || (t.rlsEnabled && (rules.some((p) => autoFixable(t, p)) || columnLock))) {
      changed.add(`${t.schema}.${t.name}`);
    }
  }
  for (const v of schema.views) {
    if (!v.materialized && !v.securityInvoker && v.apiReadable) changed.add(`${v.schema}.${v.name}`);
  }
  for (const f of schema.functions) {
    if (f.readsAuthUsers && (f.anonCanExecute || f.authenticatedCanExecute)) changed.add(`${f.schema}.${f.name}()`);
  }
  return changed;
}

function ownerWritable(t: Table): boolean {
  return t.ownerColumns.length === 1 && !t.sensitive;
}

function accessRules(t: Table): string[] {
  const q = qualified(t.schema, t.name);

  if (t.ownerColumns.length === 1) {
    const me = `(select auth.uid()) = ${quoteIdent(t.ownerColumns[0])}`;
    if (t.sensitive) {
      return [
        `-- ${t.privilege ? "Roles or memberships" : "Billing records"}: users can read their own rows; only your server or an admin function can change them.`,
        ...rule(q, "guard: owners can read", `for select to authenticated using (${me})`),
      ];
    }
    const lines = [
      ...rule(q, "guard: owners can read", `for select to authenticated using (${me})`),
      ...rule(q, "guard: owners can add", `for insert to authenticated with check (${me})`),
      ...rule(q, "guard: owners can update", `for update to authenticated using (${me}) with check (${me})`),
      ...rule(q, "guard: owners can delete", `for delete to authenticated using (${me})`),
    ];
    if (t.ownerColumns[0] === "id") {
      lines.unshift("-- Each user can only see their own row. If other users need to see these rows (e.g. names on posts), add a read rule for that.");
    }
    return lines;
  }

  if (t.ownerColumns.length > 1) {
    const anyOwner = `(select auth.uid()) in (${t.ownerColumns.map(quoteIdent).join(", ")})`;
    return [
      `-- Several user columns (${t.ownerColumns.join(", ")}): users can read rows they are part of. Add write rules that match how your app works.`,
      ...rule(q, "guard: participants can read", `for select to authenticated using (${anyOwner})`),
    ];
  }

  return [
    "-- No owner column found: read-only for now. Remove this rule if the table should not be public.",
    ...rule(q, "guard: public read-only", "for select to anon, authenticated using (true)"),
  ];
}

function columnGrants(t: Table): string[] {
  const q = qualified(t.schema, t.name);
  const insertable = t.columns.map((c) => c.name).filter((c) => !t.protectedColumns.includes(c));
  const updatable = insertable.filter((c) => !t.ownerColumns.includes(c) && !["id", "created_at", "inserted_at"].includes(c));
  const lines = [
    `-- Users may edit only safe columns of ${t.schema}.${t.name}; ${t.protectedColumns.join(", ")} can only be changed by your server.`,
    `revoke insert, update on ${q} from anon, authenticated;`,
  ];
  if (insertable.length > 0) lines.push(`grant insert (${insertable.map(quoteIdent).join(", ")}) on ${q} to authenticated;`);
  if (updatable.length > 0) lines.push(`grant update (${updatable.map(quoteIdent).join(", ")}) on ${q} to authenticated;`);
  return lines;
}

function rule(table: string, name: string, definition: string): string[] {
  return [
    `drop policy if exists ${quoteIdent(name)} on ${table};`,
    `create policy ${quoteIdent(name)} on ${table} ${definition};`,
  ];
}
